### ISSUE TITLE
Code check in?

### ISSUE THREAD

**Issue by poshaughnessy** [aframevr/slackoverflow#1]
Hi! I'm hoping to set up a bot like the one in the A-Frame Slack, for our own Slack, to notify us if people ask relevant questions.

I looked through the code here and also in https://github.com/mkungla/slackoverflow but it looks like it's just the boilerplate and the actual code for the API and bot itself is missing?

If it might possible to share it, that'd be great! Thanks.

**Comment by poshaughnessy** [comment]
No worries, I found [donmccurdy/stack-overflow-feed-bot](https://github.com/donmccurdy/stack-overflow-feed-bot) !

**Comment by ngokevin** [comment]
@mkungla Is the code for the bot there?

**Comment by mkungla** [comment]
@ngokevin and @poshaughnessy no working bot which we are using is not donmccurdy/stack-overflow-feed-bot so I should check actual bot in here, will try to find coming days time to pick that up and update this repo.

**Comment by mkungla** [comment]
@poshaughnessy so can also reopen this and I notify you when I have checked in our bot.

**Comment by mkungla** [comment]
@poshaughnessy this can be closed now let me know if you have any questions
